### ISSUE TITLE
Unified class implementations for java.base

### ISSUE THREAD

**Issue by dmlloyd** [qbicc/qbicc-class-library#5]
Provide platform-unified implementations for the following files (please link issue and/or PR #s for each task):

- [x] java/io/DefaultFileSystem.java - aeead9d03209f0ac8151e7800c2e7d8830169442
- [x] java/lang/ClassLoaderHelper.java
- [x] java/lang/ProcessEnvironment.java
- [x] java/lang/ProcessImpl.java
- [x] java/lang/Terminator.java
- [x] #356
- [ ] java/net/DefaultInterface.java
- [ ] java/net/PlainSocketImpl.java
- [ ] jdk/internal/loader/ClassLoaderHelper.java
- [x] jdk/internal/loader/FileURLMapper.java - a63b54682685c7e77721e26e37ca6dd36276f989
- [x] jdk/internal/misc/OSEnvironment.java - 608319fc2f2aa9137f6d3c22fdd99af46fa56680
- [ ] jdk/internal/platform/SystemMetrics.java
- [x] sun/net/NetHooks.java - 7cbac1c1cfb4f40d5c26588524aa8ba29aec0e58
- [ ] sun/net/PortConfig.java
- [ ] sun/net/dns/ResolverConfigurationImpl.java
- [x] #300
- [x] sun/net/www/protocol/http/ntlm/NTLMAuthentication.java - 78d94c651e0241b6531d661c401f0e88adc01886
- [ ] sun/net/www/protocol/jar/JarFileFactory.java
- [x] sun/nio/ch/DatagramDispatcher.java - 1aca340d0f308205bd41a4e84c95734516497b6b
- [x] sun/nio/ch/DefaultAsynchronousChannelProvider.java - e185223f6bfa0f87e378ac928454f5d845af3ab0
- [x] sun/nio/ch/DefaultSelectorProvider.java - e185223f6bfa0f87e378ac928454f5d845af3ab0
- [x] sun/nio/ch/FileDispatcherImpl.java - 7cbac1c1cfb4f40d5c26588524aa8ba29aec0e58
- [x] sun/nio/ch/FileKey.java - f8a70f4b2e92baecd64c47f80ae2a8afc7069ec1
- [ ] sun/nio/ch/NativeThread.java
- [ ] sun/nio/ch/PipeImpl.java
- [ ] sun/nio/ch/SinkChannelImpl.java
- [x] sun/nio/ch/SocketDispatcher.java - 1aca340d0f308205bd41a4e84c95734516497b6b
- [x] sun/nio/ch/SocketOptionRegistry.java - 7cbac1c1cfb4f40d5c26588524aa8ba29aec0e58
- [ ] sun/nio/ch/SourceChannelImpl.java
- [x] sun/nio/fs/DefaultFileSystemProvider.java - e185223f6bfa0f87e378ac928454f5d845af3ab0
- [ ] sun/nio/fs/DefaultFileTypeDetector.java
- [x] sun/nio/fs/UnixConstants.java - 7cbac1c1cfb4f40d5c26588524aa8ba29aec0e58
- [ ] sun/print/PrintServiceLookupProvider.java
- [ ] sun/security/provider/NativePRNG.java
- [ ] sun/security/provider/NativeSeedGenerator.java
- [ ] sun/util/locale/provider/HostLocaleProviderAdapterImpl.java

**Comment by dgrove-oss** [comment]
I updated the list for Java 17 (added a few, removed others).  Going to close #261 as a duplicate of this issue
